language: cpp
sudo: required
dist: trusty

compiler: clang
addons:
apt:
  sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
  packages:
    - clang-3.7
env: COMPILER=clang++-3.7

install:
    export CXX="clang++-3.7"

script:
  - mkdir build
  - cd build
  - cmake .. && make